const emojiImages: { [key: string]: any } = {
  Avocado: require(`@/assets/emojis/avocado.webp`),
  Banana: require(`@/assets/emojis/banana.webp`),
  Bread: require(`@/assets/emojis/bread.webp`),
  Burrito: require(`@/assets/emojis/burrito.webp`),
  Cake: require(`@/assets/emojis/cake.webp`),
  Chicken: require(`@/assets/emojis/chicken.webp`),
  Dumpling: require(`@/assets/emojis/dumpling.webp`),
  Egg: require(`@/assets/emojis/egg.webp`),
  Eggplant: require(`@/assets/emojis/eggplant.webp`),
  Fries: require(`@/assets/emojis/fries.webp`),
  Grapes: require(`@/assets/emojis/grapes.webp`),
  Meat: require(`@/assets/emojis/meat.webp`),
  Pizza: require(`@/assets/emojis/pizza.webp`),
  Rice: require(`@/assets/emojis/rice.webp`),
  Spaghetti: require(`@/assets/emojis/spaghetti.webp`),
  Tangerine: require(`@/assets/emojis/tangerine.webp`),
  Watermelon: require(`@/assets/emojis/watermelon.webp`),
  Yam: require(`@/assets/emojis/yam.webp`),
  Book: require(`@/assets/emojis/book.webp`),
  Fridge: require(`@/assets/emojis/fridge.webp`),
  Default: require(`@/assets/emojis/placeholder.webp`),
};
export default emojiImages;
