const emojiImages: { [key: string]: any } = {
  Avocado: require(`@/assets/exampleemojis/avocado.png`),
  Banana: require(`@/assets/exampleemojis/banana.png`),
  Bread: require(`@/assets/exampleemojis/bread.png`),
  Burrito: require(`@/assets/exampleemojis/burrito.png`),
  Cake: require(`@/assets/exampleemojis/cake.png`),
  Chicken: require(`@/assets/exampleemojis/chicken.png`),
  Dumpling: require(`@/assets/exampleemojis/dumpling.png`),
  Egg: require(`@/assets/exampleemojis/egg.png`),
  Eggplant: require(`@/assets/exampleemojis/eggplant.png`),
  Fries: require(`@/assets/exampleemojis/fries.png`),
  Grapes: require(`@/assets/exampleemojis/grapes.png`),
  Meat: require(`@/assets/exampleemojis/meat.png`),
  Pizza: require(`@/assets/exampleemojis/pizza.png`),
  Rice: require(`@/assets/exampleemojis/rice.png`),
  Spaghetti: require(`@/assets/exampleemojis/spaghetti.png`),
  Tangerine: require(`@/assets/exampleemojis/tangerine.png`),
  Watermelon: require(`@/assets/exampleemojis/watermelon.png`),
  Yam: require(`@/assets/exampleemojis/yam.png`),
  Book: require(`@/assets/exampleemojis/book.png`),
  Default: require(`@/assets/exampleemojis/placeholder.png`),
};
export default emojiImages;
